name: Auto update analytics brief
on:
  schedule:
    - cron: "0 13 * * 1,4"   # Mon & Thu 09:00 ET ≈ 13:00 UTC (adjust if needed)
  workflow_dispatch: {}       # allow manual run from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # allow committing updates.json with GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install rss-parser node-fetch@3 date-fns --save

      - name: Fetch updates & build JSON
        run: node scripts/fetch_updates.js

      - name: Commit updates.json
        run: |
          if [[ -n "$(git status --porcelain updates.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add updates.json
            git commit -m "Auto-update: refresh updates.json"
            git push
          else
            echo "No changes to commit."
          fi
